api-key-controllers:
    resource:
        path: ../src/ApiKey/Transport/Controller/Api/
        namespace: App\ApiKey\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

role-controllers:
    resource:
        path: ../src/Role/Transport/Controller/Api/
        namespace: App\Role\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

tool-controllers:
    resource:
        path: ../src/Tool/Transport/Controller/Api/
        namespace: App\Tool\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

user-controllers:
    resource:
        path: ../src/User/Transport/Controller/Api/
        namespace: App\User\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

configuration-controllers:
    resource:
        path: ../src/Configuration/Transport/Controller/Api/
        namespace: App\Configuration\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

menu-controllers:
    resource:
        path: ../src/Menu/Transport/Controller/Api/
        namespace: App\Menu\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

blog-controllers:
    resource:
        path: ../src/Blog/Transport/Controller/Api/
        namespace: App\Blog\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

messenger-controllers:
    resource:
        path: ../src/Messenger/Transport/Controller/Api/
        namespace: App\Messenger\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

quiz-controllers:
    resource:
        path: ../src/Quiz/Transport/Controller/Api/
        namespace: App\Quiz\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

crm-controllers:
    resource:
        path: ../src/Crm/Transport/Controller/Api/
        namespace: App\Crm\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
